version: "3.1"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    working_dir: /WWW
    volumes:
      - ../src:/WWW
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=demo
      - MYSQL_USER=anhvu
      - MYSQL_PASSWORD=keykey90
    ports:
      - "8082:3306"

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /WWW
    volumes:
      - ../src:/WWW
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    ports:
      - 8080:80
      - 443:443

  app:
    build: php
    container_name: app
    working_dir: /WWW
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
    volumes:
      - ../src:/WWW
      - ./php/php-overrides.ini:/usr/local/etc/php/conf.d/php-ini.ini
